<?php
/**
 * 抽奖控制器
 * Created by PhpStorm.
 * User: yule
 * Date: 2017/2/4
 * Time: 14:42
 */

namespace Plugin\Controller;

use Think\Controller;
//use Base\Controller\HomeBaseController;


class LuckydrawController extends Controller
{
    private $drawMod,$prizeMod, $resultsMod;
    /*public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->drawMod = M("Lucky_draw");
        $this->prizeMod = M("Lucky_prize");
        $this->resultsMod = M("Lucky_results");
    }*/

    function __construct()
    {
         parent::__construct(); // TODO: Change the autogenerated stub
        $this->drawMod = M("Lucky_draw");//抽奖活动
        $this->prizeMod = M("Lucky_prize");//奖品表
        $this->resultsMod = M("Lucky_results");// 抽奖人员名单
    }

    public function index(){
        $draw_id = 1;
        //$res_log = $this->resultsMod->where('is_win != 0 && draw_id='.$draw_id)->select();

        //$Member = M("Member");
        $User = M("User");
        $res_log = $User->where(array('id'=>array('elt',10)))->select();
        //var_dump($res_log);exit();

        //中奖用户名和奖品名称
        foreach($res_log as $key =>$value){
            //$user = $Member->where('id='.$value['member_id'])->getField('username');
            //$data[$key]['name'] = $this->hidtel($user);
            $data[$key]['name'] = $value['name'];
//            $data[$key]['prize'] = $this->prizeMod->where('id='.$value['is_win'])->getField('prize');
            $data[$key]['prize'] = $value['email'];
        }
        //var_dump($data);exit();
        $this->assign('data_log',$data);
        $this->display();
    }

    //账号手机号替换*号
    public function hidtel($phone){
        $IsWhat = preg_match('/(1[3578]{1}[0-9])[0-9]{4}([0-9]{4})/i',$phone); //固定电话
        if($IsWhat == 1){
            return  preg_replace('/(1[358]{1}[0-9])[0-9]{4}([0-9]{4})/i','$1****$2',$phone);
        }else{
            return  substr_replace($phone,'****',2,4);
        }
    }

    //抽奖控制器
    //public function choujiang(){
    public function luck_draw(){

        $draw_id = 1;//活动ID
        $m_id = 88;//会员ID
        //$m_id = rand(10,60);//会员ID

        /***************************验证********************************/
        $drawrs = $this->drawMod->where('id='.$draw_id)->find();//查询抽奖
        if(!$drawrs){
            $this->ajaxReturn(array('yes'=>"活动不存在或已删除",'v'=>-2));
            die();
        }

        /*if($drawrs['start_time'] > time() || $drawrs['end_time'] < time()){
            $this->ajaxReturn(array('yes'=>"活动未开始或已结束",'v'=>-3));
            die();
        }*/


        //获取当天的年份
        $y = date("Y");//获取当天的月份
        $m = date("m");//获取当天的号数
        $d = date("d");//将今天开始的年月日时分秒，转换成unix时间戳(开始示例：2015-10-12 00:00:00)
        $todayTime= mktime(0,0,0,$m,$d,$y);

        //检查当天用户的抽奖次数
        // TODO 抽奖的规则确定
        //$userlog = $this->resultsMod->where('draw_id = '.$draw_id.' && member_id ='.$m_id .'&& add_time > '.$todayTime)->order('add_time desc')->select();
        //$userlog_count = $this->resultsMod->where('draw_id = '.$draw_id.' && member_id ='.$m_id .'&& add_time > '.$todayTime)->count();
        $userlog_count = $this->resultsMod->where(array('draw_id'=>$draw_id,'member_id'=>$m_id,'add_time'=>array('egt',$todayTime)))->count();
        //echo $this->resultsMod->getLastSql();exit();
        /*if(count($userlog) > 10){
            $this->ajaxReturn(array('yes'=>"你今天的抽奖次数已经用完",'v'=>-1));
            die();
        }*/
        if($userlog_count > 10){
            $this->ajaxReturn(array('yes'=>"你今天的抽奖次数已经用完",'v'=>-1));
            die();
        }



        /***************************验证 END********************************/



        /***************************抽奖********************************/
        $prize_arr = $this->prizeMod->where('draw_id='.$draw_id.' && remain_num !=0')->select();//找出剩下数量不为0的
        foreach ($prize_arr as $key => $val) {
            $vv = $val['odds'] / 100 * 10000 ;//几率除以100，乘以10000
            $arr[$key+1] = $vv;//抽奖从0开始循序，不允许存在空的$key
        }
        //var_dump($arr);exit();
        $proSum = array_sum($arr);//抽奖值字段总和
        $shang = 10000-$proSum;//没有奖的概率
        /*提醒！ 
         *①奖品表没设置谢谢参与(没中奖选项),随着奖品数量减少到0,无奖概率是逐渐提高替代原先奖品的概率，直至100%
         *②如果奖品表设置无奖的选项，则下面的无奖励概率不需要用到，变为奖品表无奖项目来作为补充替代
         */
        //如果不到100%，则剩下的为无奖概率
        if($shang){
            $arr[] = $shang;
            $prize_arr[] = array(
                'prize'=>"元宵快乐（谢谢参与）",
                'odds' => $shang
            );
        }
        //var_dump($arr);exit();
        //var_dump($prize_arr);exit();


        $rid = $this->get_rand($arr); //根据概率获取奖项id

        /***************************抽奖 END********************************/

        /***************************结果拼接********************************/
        $res['r'] = $rid-1; //奖品ID
        $win = isset($prize_arr[$rid-1]['id']) ? $prize_arr[$rid-1]['id']:0;
        $rslog = $this->get_result($draw_id, $m_id, $prize_arr[$rid-1]['prize'], $win);//记录抽奖信息

        if($win) {
            //如果中奖了，减少奖品数量
            $this->prizeMod->where('id=' . $prize_arr[$rid - 1]['id'])->setDec('remain_num', 1);//数量减一
        }

        $res['yes'] = $prize_arr[$rid-1]['prize']; //中奖项
        $res['v'] = isset($prize_arr[$rid-1]['id']) ? $prize_arr[$rid-1]['id']:0 ;//是否中奖
        unset($prize_arr[$rid-1]); //将中奖项从数组中剔除，剩下未中奖项
        shuffle($prize_arr); //打乱数组顺序
        for($i=0;$i<count($prize_arr);$i++){
            $pr[] = $prize_arr[$i]['prize'];
        }
        $res['no'] = $pr;//没中奖的
//        echo json_encode($res);
        dump($res);exit();
        $this->ajaxReturn($res);

    }

    /**
     * 创建抽奖记录
     * @param $drawId 项目ID
     * @param $memberId 中奖会员ID
     * @param string $described 奖品描述
     * @param int $wining 是否中奖,奖品ID，未中为0
     * @return mixed
     */
    private function get_result($drawId,$memberId,$described='',$wining=0){
        $data['draw_id'] = $drawId;
        $data['member_id'] = $memberId;
        $data['result_described'] = $described;
        $data['is_win'] = $wining;
        $data['add_time'] = time();
        $res = $this->resultsMod->add($data);
        return $res;
    }

    /**
     * 抽奖算法
     * 一个几率数字的数组，数字int类型。
     * @param $proArr
     * @return int|string
     */
    private function get_rand($proArr) {
        $result = '';

        //概率数组的总概率精度
        $proSum = array_sum($proArr);

        //概率数组循环
        foreach ($proArr as $key => $proCur) {
            $randNum = mt_rand(1, $proSum);
            if ($randNum <= $proCur) {
                $result = $key;
                break;
            } else {
                $proSum -= $proCur;
            }
        }
        unset ($proArr);

        return $result;
    }

}