<?php
/**
 * 抽奖后台
 * Created by PhpStorm.
 * User: yule
 * Date: 2017/2/5
 * Time: 10:30
 */

namespace Plugin\Controller;

use Think\Controller;
//use Base\Controller\BaseController;

class LuckydrawSystemController extends Controller
{
    private $drawMod,$prizeMod, $resultsMod;
    /*public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->drawMod = M("Lucky_draw");
        $this->prizeMod = M("Lucky_prize");
        $this->resultsMod = M("Lucky_results");

        if(!$this->cur_user_info){
            $this->redirect("Admin/Index/index");//跳去登陆
        }
    }*/

    function __construct()
    {
         parent::__construct(); // TODO: Change the autogenerated stub
        $this->drawMod = M("Lucky_draw");//中奖活动
        $this->prizeMod = M("Lucky_prize");//奖品表
        $this->resultsMod = M("Lucky_results");// 会员名单
                                               // 
        if(!$this->cur_user_info){
            $this->error("Admin/Index/index");//跳去登陆
        }
    }

    public function index(){
		
    }

    //活动列表
    public function drawList(){
        $User = M("Lucky_draw");
        $count = $User->where($map)->count();
        $page = $this->page($count, 20);
        $list = $User->where($map)->limit($page->firstRow . ',' . $page->listRows)->order('id DESC')->select();
        foreach($list as $k=>$v){
            if($v['start_time'] > time()){
                $list[$k]['status'] = '未开始';
            }
            if($v['end_time'] < time()){
                $list[$k]['status'] = '已过期';
            }
            if($v['start_time'] < time() && $v['end_time'] > time()){
                $list[$k]['status'] = '正在进行';
            }
        }
        $this->assign('list', $list);
        $this->assign('count', $count);
        $this->assign('page', $page->show('Admin'));
        $this->display();
    }

    //创建抽奖活动
    public function add(){
        $id = I('get.id');
        $User = M("Lucky_draw");
        if(IS_AJAX){
            $tid = I("post.id");

            $data['title'] = I("post.title");
            $data['description'] = I("post.description");
            $start_time = I("post.start_time");
            $end_time = I("post.end_time");

            $data['start_time'] = strtotime($start_time) ;
            $data['end_time'] = strtotime($end_time) ;


            if(!empty($tid)){
                $User->where('id='.$tid)->save($data);
                $this->ajaxReturn(array('code'=>200,'msg'=>'修改成功'));
            }else{
                $data['add_time'] = time();
                $result = $User->add($data);
                if($result){
                    $this->ajaxReturn(array('code'=>200,'msg'=>'创建成功'));
                }else{
                    $this->ajaxReturn(array('code'=>400,'msg'=>'操作失败'));
                }
            }



        }else{

            if($id){
                $info = $User->where('id='.$id)->find();
                $this->assign('info',$info);
            }
            $this->display();
        }
    }


    //设置属性
    public function prize_add(){
        $id = I('get.id');
        if(!empty($id)){
            $info = $this->drawMod->where('id='.$id)->find();
            $this->assign('info',$info);

            $list = $this->prizeMod->where('draw_id='.$id)->select();

            $this->assign('list',$list);
            $this->display();
        }
    }

    //保存奖品
    public function prize_addAjax(){
        $data['draw_id'] = I("get.drawId");
        if(empty($data['draw_id'])){
            $this->ajaxReturn(array("code"=>404,"msg"=>"没有活动ID"));exit();
        }
        $data['prize'] = I("get.prize");
        $data['odds'] = I("get.odds");
        $number = I("get.number");
        $data['number'] = $number;
        $data['remain_num'] = $number;
        $data['add_time'] = time();

        $pr_id = I("get.prize_id");
        if(!empty($pr_id)){
            $this->prizeMod->where('id='.$pr_id)->save($data);
            $this->ajaxReturn(array('code'=>200,'msg'=>'修改成功'));
        }else{
            $result = $this->prizeMod->add($data);
            if($result){
                $this->ajaxReturn(array('code'=>200,'msg'=>'创建成功'));
            }else{
                $this->ajaxReturn(array('code'=>400,'msg'=>'操作失败'));
            }
        }
    }

    //删除奖品
    public function prize_deleteAjax(){
        $prize_id = I("get.prize_id");
        if($prize_id){
            $this->prizeMod->delete($prize_id);
            $this->ajaxReturn(array('code'=>200,'msg'=>'删除成功'));
        }else{
            $this->ajaxReturn(array('code'=>404,'msg'=>'没有可删除的'));
        }
    }

    //抽奖记录
    public function result_log(){
        $draw_id = I('get.draw_id');
        if(empty($draw_id)){
            $this->error("抽奖ID不能为空");exit();
        }
        $iswin = I("get.is_win");
        if($iswin != 0){
            $map['is_win'] = array('neq',0);//不等于0，中奖的
            $this->assign('iswin',1);
        }else{
            $this->assign('iswin',0);
        }
        $map['draw_id'] = $draw_id;
        $count = $this->resultsMod->where($map)->count();
        $page = $this->page($count, 20);
        $list = $this->resultsMod->where($map)->limit($page->firstRow . ',' . $page->listRows)->order('id DESC')->select();
        foreach($list as $k=>$v){
            if($v['member_id']) {
                $Member = M("member");
                $list[$k]['minfo'] = $Member->where('id=' . $v['member_id'])->find();
            }
        }
        $this->assign('draw_id',$draw_id);
        $this->assign('list', $list);
        $this->assign('count', $count);
        $this->assign('page', $page->show('Admin'));
        $this->display();
    }


    /**
	 * 奖品发放确认
     * @return type
     */
    public function get_result_sure()
    {
        $rid = I("get.rid");
        if($rid){
            $rs = $this->resultsMod->where('id='.$rid)->find();
            if($rs){
                if($rs['is_win'] != 0){
                    if($rs['is_sure']!=0){
                        $msg = array('code'=>400,'msg'=>'奖品已发');
                    }else{
                        //更新
                        $data['is_sure'] = 1;
                        $data['bj_time'] = time();
                        $this->resultsMod->where('id='.$rid)->data($data)->save(); // 根据条件保存修改的数据
                        $msg = array('code'=>200,'msg'=>'操作成功，奖品已发');
                    }
                }else{
                    $msg = array('code'=>500,'msg'=>'用户未中奖');
                }
            }else{
                $msg = array('code'=>404,'msg'=>'记录不存在');
            }
        }
        $this->ajaxReturn($msg);
    }

    /**
     * 分页
     * @param type $Total_Size
     * @param type $Page_Size
     * @param type $Current_Page
     * @param type $listRows
     * @param type $PageParam
     * @param type $PageLink
     * @param type $Static
     * @return \Page
     */
    protected function page($Total_Size = 1, $Page_Size = 0, $Current_Page = 1, $listRows = 6, $PageParam = '', $PageLink = '', $Static = FALSE) {
        if ($Page_Size == 0) {
            $Page_Size = C("PAGE_LISTROWS");
        }
        if (empty($PageParam)) {
            $PageParam = C("VAR_PAGE");
        }
        $Page = new \Org\Util\Page($Total_Size, $Page_Size, $Current_Page, $listRows, $PageParam, $PageLink, $Static);
        $Page->SetPager('Admin', '<span class="page_z">第<em>{pageindex}</em>页，共<em>{pagecount}</em>页</span>&nbsp;{first}{prev}&nbsp;{next}{last}&nbsp;转到 &nbsp;{jump}', array("listlong" => "", "first" => '<i class="icon-step-backward"></i>', "last" => '<i class=" icon-step-forward"></i>', "prev" => '<i class="icon-backward"></i>', "next" => '<i class="icon-forward"></i>', "list" => "*", "disabledclass" => ""));
        return $Page;
    }

}